import type {
  SearchResponse,
  SearchSummary,
  SettingValue,
  SourceStatus,
} from "@/types/api";

export const sourceFixture: SourceStatus = {
  key: "mock",
  name: "Deterministic mock",
  kind: "development",
  category: "developer_community",
  support_level: "supported",
  coverage_label: "Explicit deterministic test mode",
  capabilities: {
    keyword_search: true,
    phrase_search: true,
    hashtag_search: true,
    author_search: false,
    recent_search: true,
    historical_search: true,
    language_filter: true,
    date_filter: true,
    public_posts: true,
    comments: false,
    engagement_metrics: true,
    pagination: false,
    requires_credentials: false,
    requires_approval: false,
    paid_access: false,
    public_timeline: false,
    hashtag_timeline: false,
    authenticated_fulltext_search: false,
    instance_scoped: false,
    content_types: ["posts"],
    search_modes: [],
    sort_modes: [],
    acquisition_modes: ["DIRECT_API"],
    web_index_search: false,
    official_embed: false,
    historical_index: false,
  },
  configuration_state: "configured",
  active_acquisition_mode: "DIRECT_API",
  enabled: true,
  configured: true,
  status: "healthy",
  detail: null,
  confidence: 70,
  last_checked_at: null,
  last_success_at: null,
  recent_failure: null,
  failure_category: null,
  http_status: 200,
  average_latency_ms: 1,
  last_latency_ms: 1,
  last_result_count: 1,
  last_normalized_count: 1,
  last_malformed_count: 0,
  request_count: 1,
  failure_count: 0,
  configuration: {},
};

export const summary: SearchSummary = {
  id: "session-1",
  original_query: "public policy",
  normalized_query: "public policy",
  detected_language: "en",
  status: "partial",
  sources: ["mock", "youtube"],
  result_count: 1,
  unique_count: 1,
  duration_ms: 125,
  started_at: "2026-01-01T00:00:00Z",
  completed_at: "2026-01-01T00:00:01Z",
  warnings: [
    {
      source: "youtube",
      code: "unconfigured",
      message: "YOUTUBE_API_KEY is not configured",
      retryable: false,
      status_code: null,
    },
  ],
  parameters: {
    query: "public policy",
    sources: ["mock", "youtube"],
    time_range: "7d",
    language: "all",
    limit: 50,
    exact_phrase: false,
    sort: "best_match",
    content_types: [],
    has_media: null,
    has_links: null,
    hashtags: [],
    source_options: {},
    search_mode: "balanced",
    source_selection: "explicit",
  },
};

export const searchResponse: SearchResponse = {
  session: summary,
  results: [
    {
      id: "item-1",
      source: "mock",
      source_type: "fixture",
      acquisition_mode: "DIRECT_API",
      acquisition_modes_seen: ["DIRECT_API"],
      indexed_public_web_coverage: false,
      discovery_support: null,
      discovery_engines: [],
      evidence_completeness: "RICH",
      evidence_completeness_score: 0.9,
      external_id: "mock-1",
      canonical_url: "https://example.invalid/record",
      author: "Fixture analyst",
      author_handle: "fixture",
      author_verified: false,
      title: "Public policy institutional briefing",
      text: "A deterministic public policy record used to validate MIRSAD result rendering and score explanation.",
      relevant_snippet:
        "A deterministic public policy record used to validate MIRSAD result rendering and score explanation.",
      highlight_ranges: [{ start: 16, end: 29 }],
      semantic_only_match: false,
      published_at: "2026-01-01T00:00:00Z",
      fetched_at: "2026-01-01T00:01:00Z",
      language: "en",
      hashtags: ["policy"],
      mentions: null,
      media_type: "post",
      like_count: 10,
      view_count: null,
      comment_count: null,
      share_count: null,
      repost_count: null,
      reaction_count: null,
      raw_metrics: { likes: 10 },
      normalized_engagement: 42,
      social_reach: null,
      score: 78.5,
      matched_terms: ["public", "policy"],
      duplicate_group_id: "duplicate-1",
      duplicate_count: 1,
      related_sources: ["mock", "rss"],
      cluster_id: "cluster-1",
      explanation: {
        final_score: 78.5,
        relevance: 95,
        freshness: 80,
        engagement: 42,
        source_confidence: 60,
        cross_source_presence: 40,
        novelty: 100,
        spam_penalty: 0,
        matched_terms: ["public", "policy"],
        supporting_signal_factor: 1,
        pre_penalty_score: 82.5,
        weighted_components: {
          relevance: 33.25,
          freshness: 18,
          engagement: 9,
          source_confidence: 8,
          cross_source_presence: 4.25,
          novelty: 10,
        },
        lexical_relevance: 95,
        semantic_relevance: null,
        semantic_similarity: null,
        semantic_weight: 0,
        secondary_quality_budget: 0.65,
        ranking_strategy: "lexical_explainable",
        relevance_features: {
          exact_full_query: 100,
          query_token_coverage: 100,
        },
        source: "mock",
        fetched_at: "2026-01-01T00:01:00Z",
        published_at: "2026-01-01T00:00:00Z",
        duplicate_group_id: "duplicate-1",
      },
    },
  ],
  clusters: [
    {
      id: "cluster-1",
      representative_title: "Public policy institutional briefing",
      member_count: 1,
      source_distribution: { mock: 1 },
      platform_presence: { mock: 1 },
      platform_diversity: 1,
      first_seen_by_mirsad: "2026-01-01T00:00:00Z",
      earliest_at: "2026-01-01T00:00:00Z",
      latest_at: "2026-01-01T00:00:00Z",
      aggregate_score: 78.5,
      terms: ["public", "policy"],
      member_ids: ["item-1"],
    },
  ],
  analytics: {
    total_results: 1,
    unique_results: 1,
    source_count: 1,
    duplicate_count: 0,
    average_score: 78.5,
    search_duration_ms: 125,
    mentions_over_time: [{ timestamp: "2026-01-01T00:00:00Z", count: 1 }],
    trend_percent: 100,
    overall_trend_percent: 100,
    social_mentions_over_time: [],
    social_trend_percent: 0,
    news_mentions_over_time: [],
    news_trend_percent: 0,
    platform_distribution: { mock: 1 },
    social_source_distribution: {},
    most_active_platforms: [],
    most_engaged_results: [],
    top_hashtags: [],
    top_mentioned_accounts: [],
    platform_diversity: 0,
    category_distribution: { developer_community: 1 },
    average_social_reach: null,
    top_related_terms: [{ term: "policy", count: 1 }],
    language_distribution: { en: 1 },
    publication_time_distribution: { last_24h: 1 },
    score_distribution: { "60-79": 1 },
    cluster_distribution: { "1": 1 },
    bucket: "1h",
  },
};

export const settingsFixture: SettingValue[] = [
  { key: "general.default_result_limit", value: 50, category: "general" },
  { key: "search.default_time_range", value: "7d", category: "search" },
  { key: "ranking.relevance", value: 0.35, category: "ranking" },
  { key: "ranking.freshness", value: 0.2, category: "ranking" },
  { key: "ranking.engagement", value: 0.15, category: "ranking" },
  { key: "ranking.source_confidence", value: 0.1, category: "ranking" },
  { key: "ranking.cross_source_presence", value: 0.1, category: "ranking" },
  { key: "ranking.novelty", value: 0.1, category: "ranking" },
  { key: "language.default", value: "en", category: "language" },
  { key: "appearance.theme", value: "system", category: "appearance" },
  { key: "data.retention_days", value: 90, category: "data" },
];
